### Search Burgers by Name

GET http://localhost:8080/api/burgers/search?name=2

### Search Burgers by ingredient Name

GET http://localhost:8080/api/burgers/search/by-ingredient?name=jal

### List All starting Letters of Burger Names

GET http://localhost:8080/api/burgers/indexes

### List all Burgers by first letter

GET http://localhost:8080/api/burgers/by-index?letter=t

### Lookup full BURGER details by id

GET http://localhost:8080/api/burgers/1

### Lookup a random Burger

GET http://localhost:8080/api/burgers/random

### Create Burger

POST http://localhost:8080/api/burgers
Content-Type: application/json

{
  "name": "Test Burger 1",
  "description": "Tasty Test Burger 1.",
  "image_url": null,
  "ingredients": [
    {
      "id": 7,
      "name": "lettuce"
    },
    {
      "id": 15,
      "name": "pickles"
    },
    {
      "id": 18,
      "name": "tomato"
    }
  ]
}

###








