
# curl -X POST http://localhost:8080/upload
#  -F "file=@/Users/appleboy/test.zip"
#  -H "Content-Type: multipart/form-data"

POST http://localhost:8080/api/images
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="ygawxmra98j182aegps4d5rrwhtz4u.jpeg"

< D:\burgers\ygawxmra98j182aegps4d5rrwhtz4u.jpeg
--WebAppBoundary--

###

